### ISSUE TITLE
Using this and loving it

### ISSUE THREAD

**Issue by mrjjwright** [danielearwicker/bidi-mobx#10]
I am using this extensively and at work.  Just created a custom adaptor for a complex scenario, so elegant.  Bidis are magical tools for the observable graph and input systems.  (Also I am starting to speak "generics".  :)

**Comment by danielearwicker** [comment]
Awesome. I'm also using it at work now, building an editor for laying out dashboard widgets, similar to the Azure one. It's a lot of fun! The majority of the UI is declarative and functional, and yet when it is more convenient to switch to mutating a model then I can do that and everything still works.

**Comment by mrjjwright** [comment]
It's so great for editor work.  I am building an editor with it too.
