### ISSUE TITLE
System for formatting text as it's being written

### ISSUE THREAD

**Issue by gkaemmer** [danielearwicker/bidi-mobx#13]
Firstly, I'm very excited about this library--the API is very slick and the philosophy is 👍.

I'm taking a look at more complicated text inputs, and wondering about a better way of rendering things like credit card or phone fields.

My question: is there an easy way of "formatting" input text before it gets rendered in its text box? A simple example is preventing the user from typing more than 2 digits into a field. A more complicated example might look something like [Cleave](https://nosir.github.io/cleave.js/).

So far, the only method I've come up with is custom input components that change `e.target.value` before passing it to `this.props.value.set`. This essentially takes a view model and "filters" it into another view model:
```
@observer
export default class TwoCharTextInput extends Component {

  @action change(value) {
    const newValue = value.substring(0, 2); // Limit field to 2 characters
    this.props.value.set(newValue);
  }

  render() {
    const {value, ...props } = this.props;
    return (
      <input
        onChange={e => {
          this.change(e.target.value);
        }}
        value={value.get()}
        {...props}
      />
    );
  }
}
```
The tough thing here is running the same filter when the actual model changes. For example, what if the model value now has length > 2? Should the view model be set accordingly? 

It almost seems like there could be a third (optional) adaptor method `filter`, which takes a view model, and returns another view model that has been capped at 2 characters.

Does anyone have any thoughts about how better to approach this?

**Comment by danielearwicker** [comment]
It sounds possible. An adaptor without a `filter` method would be equivalent to `filter: v => v;`. The chain of adaptors would compose - not sure in which direction (it could be important what order they are applied in and it could be left to right or right to left).

However it's worth thinking carefully about whether this makes sense. Input fields that fix their contents as you type are harder to make convenient than it first seems. It's much easier to make them annoying! I discuss this a bit in [notes.md](https://github.com/danielearwicker/bidi-mobx/blob/master/notes.md).

**Comment by gkaemmer** [comment]
Not sure what you mean about adaptor being equivalent. Do you mean you could implement something like this using the current adaptor API?

I agree that live-formatting is weird and opens pandora's box for form UIs. Might be a good argument for why it shouldn't (ever) be easy. But I also know how pleasant it can be to finish typing a credit card number and to find it nicely chunked with subtle spacing (a la [Stripe Checkout](https://stripe.com/checkout)).

But, this is probably better solved on a case-by-case basis than with more changes to the `bidi-mobx` API. After playing around more, I found it is very straightforward to bind a Cleave input to a boxed view value:
```
export default class CreditCardInput extends Component {
  render() {
    const { value, ...props } = this.props;
    return (
      <Cleave
        value={value.get()}
        onChange={e => value.set(e.target.rawValue)}
        options={{ creditCard: true }}
        {...props}
      />
    );
  }
}
```
With a simple `field(stringLimits(16, 16))`, this formatted credit card value can be validated and updated by `bidi-mobx`, satisfying 90+% of my use cases.

**Comment by danielearwicker** [comment]
Yep, that sounds much better. Sorry my thinking aloud was poorly explained, I was just thinking about if a `filter` method was added to the adaptor interface, how would several such adaptors compose. But your new approach feels more suitable anyway.
