### ISSUE TITLE
React @types conflict

### ISSUE THREAD

**Issue by mrjjwright** [danielearwicker/bidi-mobx#3]
When compiling in webpack with `bidi-mobx` and the following line in my own package.json 

`"@types/react": "^15.0.1",`

I get about 200 errors something like:

`error TS2403: Subsequent variable declarations must have the same type.  Variable 'feSpecularLighting' must be of type 'SVGProps', but here has type 'SVGProps'.`

I noticed the bidi-mobx react @types dependency is  `"@types/react": "0.0.0",` and the declaration file it pulls in is about 700 lines longer.  When I deleted the react @types under bidi-mobx the error went away.

**Comment by mrjjwright** [comment]
This is still a bit of an issue.  Mind changing this [line](https://github.com/danielearwicker/bidi-mobx/blob/master/package.json#L31) to what is above to see if it gets rid of my webpack ts loader issues?  Perhaps I just need to configure tsloader as well.

**Comment by danielearwicker** [comment]
Done. Have also moved a couple of things to `devDependencies` that should have been there.

**Comment by mrjjwright** [comment]
Fixed, thanks!
