### ISSUE TITLE
Breaks mobx

### ISSUE THREAD

**Issue by mrjjwright** [danielearwicker/bidi-mobx#4]
After yarn install this package, mobx observation stops working in my project.  Deleting the dependency on `bidi-mobx` in my package.json, and running `yarn install` and a webpack build again causes it to start working again.  I tested several times, just changing my dependency on bidi-mobx, without actually using it.  This must be a webpack build thing.

**Comment by mrjjwright** [comment]
I thinking I am making a rookie mistake and not using mobx as an external so it's not loaded twice.

See https://github.com/mobxjs/mobx/issues/763. 

Going to try to fix this and report back.

**Comment by mrjjwright** [comment]
Yep, using mobx as an external in webpack fixed this.

**Comment by danielearwicker** [comment]
Thanks, looks like I missed all the excitement. I will note this in the readme.
