### ISSUE TITLE
Don't mutate observables when setting up view model

### ISSUE THREAD

**Issue by mrjjwright** [danielearwicker/bidi-mobx#6]
This [line](https://github.com/danielearwicker/bidi-mobx/blob/master/src/field.ts#L48) is problematic with Mobx because the view model might be setup in a computed as a result of navigating a UI.  Is it possible to not call it?  If not,  no biggie.  Right now, it  is throwing for me.  Logically a view model is a derivation so it kind makes sense not to mutate in it's constructor.

**Comment by danielearwicker** [comment]
0.18.3 might help. Obviously I need to be able to initialise an observable like `this.viewState` which is the actual purpose of it (and `this.errorState` if the initial value from the model isn't valid). But I was being somewhat lazy by getting the `view` setter to do this for me, which would have the side-effect of setting the model, which is definitely wrong.

**Comment by mrjjwright** [comment]
Fixed, thanks!!
